// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BtnInstall: typeof import('./src/components/btn/install.vue')['default']
    BtnLink: typeof import('./src/components/btn/link.vue')['default']
    Github: typeof import('./src/components/Github.vue')['default']
    GlobalApi: typeof import('./src/components/GlobalApi.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Install: typeof import('./src/components/btn/install.vue')['default']
    Link: typeof import('./src/components/btn/link.vue')['default']
    Modules: typeof import('./src/components/Modules.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    Progress: typeof import('./src/components/Progress.vue')['default']
    ProgressModal: typeof import('./src/components/ProgressModal.vue')['default']
    Theme: typeof import('./src/components/Theme.vue')['default']
  }
}

export { }
